version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "imageToTextPython"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-t2kqmdtwm4ln"
s3_prefix = "imageToTextPython"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
